services:
  # 1. Auth Service
  - type: web
    name: casper-auth-service
    runtime: python
    rootDir: 
    buildCommand: 
    startCommand: AUTH_DB_PATH=./users.db uvicorn main:app --port 8100
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0

  # 2. Main Web Service
  - type: web
    name: casper-web-service
    runtime: python
    rootDir: 
    buildCommand: pip install -r requirements.txt && .sh/setup.sh
    startCommand: streamlit run casper_app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: AUTH_SERVICE_URL
        fromService:
          type: web
          name: auth-service
          property: host